name: update

on:
  schedule:
    - cron: "17 21 * * *"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Update version and x86_64-linux hashes
        run: ./scripts/update.sh
